version: '3'
services:
  app:
    image: 'fitchmultz/qbittorrentvpn:latest'
    volumes:
      - ${CONFIG_PATH}:/config
      - ${DOWNLOADS_PATH}:/downloads
      - ${DOWNLOADS_MOVIES_PATH}:/downloads/movies
      - ${DOWNLOADS_TV_PATH}:/downloads/tv
      - ${DOWNLOADS_MUSIC_PATH}:/downloads/music
      - ${DOWNLOADS_TORRENT_FILES}:/downloads/torrentfiles
      - /dev/net/tun:/dev/net/tun
    environment:
      - VPN_ENABLED=${VPN_ENABLED}
      - VPN_TYPE=${VPN_TYPE}
      - LAN_NETWORK=${LAN_NETWORK}
      - NAME_SERVERS=${NAME_SERVERS}
      - VPN_USERNAME=${VPN_USERNAME}
      - VPN_PASSWORD=${VPN_PASSWORD}
    ports:
      - "8282:8080"
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
